services:

  demo7:
    build:
      context: ./demo7
      dockerfile: Dockerfile
    image: demo7:latest
    container_name: demo7-service
    ports:
      - "8081:8080"

  dn-springboot-demo:
    build:
      context: ./dn.springboot.demo
    image: dn-springboot-demo:latest
    container_name: dn-springboot-demo-service
    ports:
      - "8082:8080"

  javaguides:
    build:
      context: ./javaguides
    image: javaguides:latest
    container_name: javaguides-service
    ports:
      - "8083:8080"

  springboot-restful-webservices:
    build:
      context: ./springboot-restful-webservices
    image: springboot-restful-webservices:latest
    container_name: springboot-restful-webservices-service
    ports:
      - "8084:8080"